a=read.table("household_power_consumption.txt",header=T,sep=";",stringsAsFactors=F)
a$Date=as.Date(a$Date,"%d/%m/%Y")
b=a[which(a$Date=="2007-02-01" |a$Date=="2007-02-02" ),]
d=as.POSIXlt(paste(b$Date,b$Time,sep=" "))
par(mfrow=c(2,2))
plot(d,c,type="l",ylab="Global Active Power(kilowatts)",xlab="")
Voltage=as.numeric(b$Voltage)
plot(Datetime,Voltage,type="l")
plot(Datetime,b$Sub_metering_1,type="n",ylab="Energy sub metering")
legend("topright",lty=1, col=c("black","red","blue"),legend = c("sub_metering_1", "sub_metering_2","sub_metering_3"),cex=.5)
points(d,b$Sub_metering_1,type='l')
points(d,b$Sub_metering_2,type='l',col="red")
points(d,b$Sub_metering_3,type='l',col="blue")
Global_reactive_power=as.numeric(b$Global_reactive_power)
plot(Datetime,Global_reactive_power,type="l")
dev.copy(png,"plot4.png")
dev.off()
par(mfrow=c(1,1))
